import { StyleSheet, Platform } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { colors } from "../../styles/color";
import {
  HeadingMediumBold,
  HeadingXxSmallBold,
  BodyTextXLarge,
  HeadingXxxSmallBold,
  LabelLargeRegular,
  BodyTextLarge,
  LabelLargeBold,
  BodyTextMedium,
  HeadingXxxxSmallBold,
} from "../../styles/typography";
import { fonts } from "../../styles/font";

const styles = StyleSheet.create({
  mainContainer: {
    width: "100%",
    height: "100%",
  },
  bodyContainer: {
    height: "100%",
    alignItems: "center",
    backgroundColor: colors.bodyBackgroundColor,
    paddingHorizontal: wp("3.35%"),
    paddingVertical: hp("3.75%"),
    justifyContent: "center",
    gap: hp("2.8%"),
  },
  innerMainTitle: {
    width: wp("93.3%"),
    height: hp("5.6%"),
    alignItems: "center",
    justifyContent: "center",
  },
  innerMainTitleText: {
    fontSize: HeadingMediumBold.size,
    lineHeight: HeadingMediumBold.lineHeight,
    color: colors.textColor,
  },
  errorTitleContainer: {
    width: wp("93.3%"),
    borderRadius: 4,
    padding: 12,
    gap: 8,
    backgroundColor: colors.errorBgColor,
    flexDirection: "row",
  },
  errorTitleText: {
    fontSize: HeadingXxxxSmallBold.size,
    lineHeight: HeadingXxxxSmallBold.lineHeight,
    color: colors.textColor,
  },
  outerContainer: {
    display: "flex",
    flexDirection: "row",
    width: wp("91.2%"),
    gap: wp("5.52%"),
    height: hp("57%"),
  },
  sideScrollDiv: {
    width: wp("22.35%"),
    height: hp("54%"),
    borderRadius: wp("0.65%"),
    borderWidth: 1,
    borderColor: colors.gray,
    overflow: "hidden",
    backgroundColor: colors.secondary,
    borderStyle: "solid",
  },
  sideTitleDiv: {
    height: hp("6.35%"),
    borderBottomWidth: 1,
    gap: hp("0.45%"),
    paddingVertical: hp("1.4%"),
    paddingHorizontal: wp("1.35%"),
    backgroundColor: colors.neutralGrayColor,
    borderColor: colors.gray,
  },
  sideTitleText: {
    backgroundColor: colors.neutralGrayColor,
    fontSize: HeadingXxSmallBold.size,
    lineHeight: HeadingXxSmallBold.lineHeight,
    color: colors.textColor,
  },
  scrollableGroup: {
    width: "auto",
  },
  scrollableGp: {
    height: "auto",
    gap: hp("1.85%"),
    paddingHorizontal: wp("1.35%"),
    paddingVertical: hp("1.85%"),
    backgroundColor: colors.secondary,
  },
  btnSideDiv: {
    display: "flex",
    flexDirection: "row",
    borderWidth: 1,
    borderRadius: wp("0.35%"),
    paddingHorizontal: wp("0.65%"),
    paddingVertical: hp("0.95%"),
    gap: hp("0.45%"),
    alignItems: "center",
    height: hp("5.85%"),
    borderColor: colors.borderColor,
    backgroundColor: colors.secondary,
    overflow: "hidden",
  },
  btnSideDivActive: {
    display: "flex",
    flexDirection: "row",
    borderWidth: 2,
    borderRadius: wp("0.35%"),
    paddingHorizontal: wp("0.65%"),
    paddingVertical: hp("0.95%"),
    gap: hp("0.45%"),
    alignItems: "center",
    height: hp("5.85%"),
    borderColor: colors.primary,
    backgroundColor: colors.neuralBlueLightColor,
    overflow: "hidden",
    textAlign: "center",
  },
  count: {
    fontSize: HeadingXxxSmallBold.size,
    color: colors.greyTextColor,
    width: wp("1.5%"),
    display: "flex",
  },
  sideText: {
    color: colors.textColor,
    fontSize: BodyTextXLarge.size,
    flex: 1,
  },
  editScrollContainer: {
    height: "auto",
    borderRadius: wp("1.35%"),
  },
  editContainer: {
    paddingVertical: hp("2.8%"),
    paddingHorizontal: wp("2%"),
    backgroundColor: colors.secondary,
    gap: hp("2.8%"),
    borderRadius: wp("1.35%"),
    ...Platform.select({
      ios: {
        shadowColor: colors.headerFooterShadowColor,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 7,
      },
      android: {
        shadowColor: colors.headerFooterShadowColor,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 7,
        elevation: 5,
      },
      web: {
        boxShadow: `0px 1px 7px 0px ${colors.headerFooterShadowColor}`,
      },
    }),
  },
  row: {
    display: "flex",
    flexDirection: "row",
    gap: wp("2.7%"),
    minHeight: hp("5.15%"),
    height: "auto",
  },
  lowerRow: {
    zIndex: -1,
  },
  lastRowContainer: {
    display: "flex",
    flexDirection: "column",
    gap: hp("1.9%"),
    zIndex: -1,
  },
  lastRowItem: {
    display: "flex",
    flexDirection: "row",
    gap: wp("2.7%"),
    minHeight: hp("5.15%"),
    height: "auto",
  },
  lastRowBtn: {
    gap: wp("2.7%"),
    width: wp("27.45%"),
    height: hp("3.75%"),
    flexDirection: "row",
  },
  labelContainer: {
    justifyContent: "center",
    width: wp("14%"),
    ...Platform.select({
      ios: {
        width: 152,
      },
    }),
  },
  labelText: {
    gap: wp("0.65%"),
    color: colors.greyTextColor,
    fontSize: HeadingXxSmallBold.size,
    backgroundColor: colors.secondary,
    lineHeight: HeadingXxSmallBold.lineHeight,
  },
  innerRowContainer: {
    height: "auto",
    justifyContent: "center",
    flex: 0.5,
  },
  dropDownIconContainer: {
    top: hp("1.02%"),
    right: wp("0.85%"),
    width: wp("2%"),
    height: hp("2.8%"),
    position: "absolute",
  },
  inputsContainer: {
    flexDirection: "row",
    backgroundColor: colors.secondary,
    gap: wp("1.35%"),
    flex: 1,
    height: "auto",
  },
  inputErrContainer: {
    flexDirection: "column",
    backgroundColor: colors.secondary,
    height: "auto",
    flex: 1,
  },
  input: {
    gap: wp("0.65%"),
    height: hp("5.15%"),
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: hp("1.2%"),
    paddingHorizontal: wp("0.75%"),
    borderColor: colors.borderColor,
    backgroundColor: colors.secondary,
  },
  inputText: {
    fontWeight: "300",
    fontSize: LabelLargeRegular.size,
    color: colors.textColor,
    fontFamily: fonts.FontRegular.fontFamily,
  },
  errText: {
    fontWeight: "300",
    fontSize: BodyTextMedium.size,
    color: colors.danger,
  },
  errLongText: {
    width: 250,
  },
  rowInput: {
    justifyContent: "center",
    flexDirection: "row",
    display: "flex",
  },
  dropDownIcon: {
    width: 24,
    height: 24,
    position: "absolute",
  },
  birthDateInputContainer: {
    backgroundColor: colors.secondary,
    flexDirection: "row",
    display: "flex",
    alignItems: "center",
  },
  birthDateInputText: {
    width: "100%",
    fontFamily: fonts.FontRegular.fontFamily,
    fontSize: LabelLargeRegular.size,
    fontWeight: "300",
    gap: wp("0.65%"),
    height: hp("5.15%"),
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: hp("1.2%"),
    paddingHorizontal: wp("0.75%"),
    borderColor: colors.borderColor,
    backgroundColor: colors.secondary,
  },
  calendarIconContainer: {
    right: 7,
    width: 24,
    height: 24,
    position: "absolute",
  },
  calendarIcon: {
    width: 20,
    height: 22,
    left: 2,
  },
  genderRadioContainer: {
    gap: wp("2%"),
    width: wp("24.1%"),
    height: hp("5.15%"),
    flexDirection: "row",
    backgroundColor: colors.secondary,
  },
  radioContainer: {
    gap: wp("0.65%"),
    width: wp("5.35%"),
    height: hp("5.15%"),
    flexDirection: "row",
    paddingVertical: hp("1.2%"),
    paddingHorizontal: 0,
    backgroundColor: colors.secondary,
  },
  radioKaitouContainer: {
    width: wp("9.4%"),
    height: hp("5.15%"),
  },
  radioPressable: {
    flexDirection: "row",
    alignItems: "center",
  },
  radioButtonIcon: {
    width: wp("2%"),
    height: hp("2.8%"),
    backgroundColor: colors.secondary,
    justifyContent: "center",
  },
  radioButton: {
    width: 18,
    height: 18,
    borderRadius: 100,
    borderColor: colors.borderColor,
    backgroundColor: colors.secondary,
  },
  selectedRadioButton: {
    borderColor: colors.primary,
  },
  radioTextContainer: {
    backgroundColor: colors.secondary,
  },
  radioText: {
    fontSize: LabelLargeRegular.size,
    lineHeight: LabelLargeRegular.lineHeight,
    color: colors.textColor,
  },
  postCodeInputsContainer: {
    gap: wp("1.35%"),
    width: wp("29.5%"),
    minHeight: hp("5.15%"),
    flexDirection: "row",
    backgroundColor: colors.secondary,
  },
  postCodeInput: {
    gap: wp("0.65%"),
    height: hp("5.15%"),
    borderWidth: 1,
    borderRadius: wp("0.5%"),
    paddingVertical: hp("1.2%"),
    paddingHorizontal: wp("0.75%"),
    borderColor: colors.borderColor,
    backgroundColor: colors.secondary,
  },
  postCodeInputText: {
    fontWeight: "300",
    fontSize: LabelLargeRegular.size,
    color: colors.textColor,
    fontFamily: fonts.FontRegular.fontFamily,
  },
  btnSearch: {
    gap: 8,
    height: hp("5.15%"),
    borderWidth: 2,
    borderRadius: wp("0.65%"),
    paddingHorizontal: wp("1.35%"),
  },
  addressInputsContainer: {
    gap: wp("1.35%"),
    flexDirection: "row",
    backgroundColor: colors.secondary,
    flex: 1,
  },
  addressInput: {
    gap: wp("0.65%"),
    height: hp("5.15%"),
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: hp("1.2%"),
    paddingHorizontal: wp("0.75%"),
    borderColor: colors.borderColor,
    backgroundColor: colors.secondary,
  },
  addressInputText: {
    fontWeight: "300",
    fontSize: LabelLargeRegular.size,
    color: colors.textColor,
    fontFamily: fonts.FontRegular.fontFamily,
  },
  btnCopy: {
    gap: wp("0.65%"),
    width: wp("3.7%"),
    height: hp("5.15%"),
    justifyContent: "center",
    borderWidth: 2,
    borderRadius: wp("0.35%"),
  },
  btnAddress: {
    gap: wp("0.65%"),
    height: hp("4.4%"),
    borderWidth: 1,
    borderRadius: wp("0.35%"),
    paddingHorizontal: 8,
    borderColor: colors.gray,
    justifyContent: "center",
  },
  addresstoastContainer: {
    backgroundColor: colors.lightTransparentBlack,
    paddingVertical: hp("0.95%"),
    paddingHorizontal: wp("1.35%"),
    gap: wp("1.35%"),
    borderRadius: wp("0.35%"),
    position: "absolute",
    alignSelf: "center",
  },
  toastText: {
    color: "white",
    fontSize: LabelLargeBold.size,
    lineHeight: LabelLargeBold.lineHeight,
  },
  tooltip: {
    position: "absolute",
    backgroundColor: colors.tooltipBackgroundColor,
    paddingVertical: hp("0.7%"),
    paddingHorizontal: wp("0.65%"),
    borderRadius: 4,
    width: wp("10.65%"),
    height: hp("4.55%"),
    gap: hp("0.95%"),
  },
  arrow: {
    position: "absolute",
    top: 40,
    left: "50%",
    marginLeft: -5,
    width: 0,
    height: 0,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 0,
    borderLeftWidth: 5,
    borderTopColor: colors.lightTransparentBlack,
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
  },
  tooltipText: {
    color: colors.secondary,
    fontSize: BodyTextLarge.size,
    lineHeight: BodyTextLarge.lineHeight,
  },
  chevronLeftButton: {
    width: 52,
    height: 52,
    borderRadius: 1000,
    padding: 12,
    gap: 8,
    backgroundColor: "rgba(99, 107, 126, 0.5)",
  },
  chevronRightButton: {
    width: 52,
    height: 52,
    borderRadius: 1000,
    padding: 12,
    gap: 8,
    backgroundColor: "rgba(99, 107, 126, 0.5)",
  },
  calendarContainer: {
    position: "absolute",
    top: 0,
    height: "auto",
  },
  errorIcon: {
    color: colors.danger,
  },
});

export default styles;
